apiVersion: v1
data:
    credentials.json: ENC[AES256_GCM,data:S6qoLQcrY0ZbmzDNNFF/YmXQYc9XXjCdoIrLATLeMs/9a376//3ObTcRhRu2/LQ5qWfRTr4/DdA2UXsjni4I2ZHAboVBMIV1R7GZUMY3NSuuSnJzhTamahsXmSVGktuemod/cmBsMZweO+gQyAk+qdzCwbnszcNSkZsVxuZ5lwUH3IDhSSQxPzoqm0tSiICqmaIpL34bsB9/N9fs0k2L2pMqmzPU5189wCzVNXW3Y7F13MpocurbfSiXhlPap6FYXXCBiBr0H3rH8BczoVTm0EP5SuNzrFqBseFSuBQvEzxsd4IZCA0x/Hd2abY=,iv:rq8q/RjOxEIkWUMvL3Qs+vIhZclOyZl1oivG1hDNrOE=,tag:+VNjbk/09SKaF7PoZwyiiw==,type:str]
kind: Secret
metadata:
    name: tunnel-credentials
sops:
    age:
        - recipient: age139rjwpu088h0a43s8xwspxpjnm9lhz29wv4zx6nzytvwxswutv6qf5vxe0
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSA1OVVCQ0x4bEZ6ZUNGMmFT
            Q2RiV01rZWI4UVB0a3oyK2JtUnVNaWlnV3dNCndQY1RCcEtKbE1kZXp6UnVnZlJO
            OWZXeDgzVWk4UFhRNjFuSVg2b2VhNFUKLS0tIGJyOXRSMU83eG8wMXRSYlJGTkhy
            TmUyZWc2MDdJUlU2UXdSVEZQaVNkeEUK+h/2YXSnXwPN8GlN8gZvHtC0N3ZoAQCr
            E9dfANPz7YjbrrvOgkMQxoG1hBZrCKTqYjoQ/MgYRHOi5hkbY5fZhA==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2025-12-08T17:49:07Z"
    mac: ENC[AES256_GCM,data:w3sXK/c+le1lXK0hAtS+uM8ZbkdZOQumLcfSdRhSLfCfqySziIC7Er7YScbNpwpTWc0TxPEvkUxZr+BV5omcS2vz5uOsv2YOxuhzkiGUU0fnZ88EzvAY3ntHXeWqsLMJDj+Y0ffrbOFFg3ur8uw7QFYKnAEDcAkv1QbIiK/ZJ/g=,iv:KvCYGuzAfdDfh2E+aFBvZhcY1YPQqtcLNkYCtqdvESg=,tag:v0J06gbsPdmzwf7e3Lm5mA==,type:str]
    encrypted_regex: ^(data|stringData)$
    version: 3.11.0
