apiVersion: v1
kind: Secret
metadata:
    name: cloudflare-api-token
    namespace: cert-manager
type: Opaque
data:
    api-token: ENC[AES256_GCM,data:YNz1NpfaO645F21erBBXqewaWpiors8fFZPjLej86xNPDDqTpcTQPwiCPbIOlPlAYMzeMkM4Xu0=,iv:gkGhXR6vvdJlgHn5MxrTLZR5DvWDFbotpGZniW73HjY=,tag:pUyTJojFnmnUwCXrk3mwAw==,type:str]
sops:
    age:
        - recipient: age139rjwpu088h0a43s8xwspxpjnm9lhz29wv4zx6nzytvwxswutv6qf5vxe0
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBxajRGSEoxNlJyV2FJcTZp
            MSs2Z3pVbldYd0RTNUJBQXN2SUNpV1llQWdnCjNvSExXTXRwaTZ6Ukc1QXB1UVdN
            YkptelNGb3hleEdBRGUyeG03TURaemMKLS0tIDdwL3Bvcm43VG9lTVp1djJVOUd4
            MnI5bXNVVjRETkg3TVRVVEQrZldDaVkKcLXDVdnniNjbKjOulWViAX9vyEqKvIFV
            7yOQel1keNWA79xOscZLIWKlRXnob6bdiAHrI7WD958Urc80TvfrIA==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2025-12-06T16:30:28Z"
    mac: ENC[AES256_GCM,data:A56i4GqMVvkHxZbjk9DA8Dyv56k0Pw2raGKpM3l27oY+WzkOw9qcvSeAp6vzxsY5ORslslKcNE7Gr3A1IBZuSAaa/oqpKJo31jUoJrnHH81/QPFNpa+aQKh/cMlIELZaJr18iZGkc3l9+4jiutIx5UlBW+Tgf8dRXRJXMnjbyZ4=,iv:ATw5xFNIsynRbf0UBKlY12oCelYGKWUbZbYv3vKwXuE=,tag:XssT1yZ5+Ads34WfdO/nVA==,type:str]
    encrypted_regex: ^(data|stringData)$
    version: 3.11.0
