apiVersion: v1
kind: Service
metadata:
  name: mariadb-seafile
  namespace: seafile
spec:
  type: ClusterIP
  selector:
    app: mariadb-seafile
  ports:
    - name: mysql
      port: 3306
      targetPort: 3306
