apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: seafile
  namespace: seafile
spec:
  interval: 5m
  chart:
    spec:
      chart: seafile
      version: "0.12.1"
      sourceRef:
        kind: HelmRepository
        name: seafile-server
        namespace: seafile
  install:
    crds: Create
  upgrade:
    crds: CreateReplace

  values:
    seafile:
      persistence:
        existingClaim: seafile-data
        storageClassName: ""

      env:
        SEAFILE_SERVER_HOSTNAME: "seafile.hansjlachmann.net"
        SEAFILE_SERVER_PROTOCOL: "https"
    db:
      type: mysql
      host: mariadb-seafile.seafile.svc.cluster.local
      port: 3306
      db_name: seafile_db
      username: seafile
      password: "password"
      root_password: "password"
      
      #mysql:
      #  host: mariadb-seafile.seafile.svc.cluster.local
      #  user: seafile
      #  password: "password"
      #  database: seafile_db

    service:
      type: ClusterIP
      port: 80

    ingress:
      enabled: false
