apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: seafile
  namespace: seafile
spec:
  interval: 5m
  chart:
    spec:
      chart: seafile
      version: "0.12.1"
      sourceRef:
        kind: HelmRepository
        name: seafile-server
        namespace: seafile
  install:
    crds: Create
  upgrade:
    crds: CreateReplace

  values:
    nginx-ingress:
      enabled: false
    
    nginxIngress:
      enabled: false
    
    ingress:
      enabled: false

    seafile:
      persistence:
        existingClaim: seafile-data
        storageClassName: ""

      env:
        SEAFILE_SERVER_HOSTNAME: "seafile.hansjlachmann.net"
        SEAFILE_SERVER_PROTOCOL: "https"

      database:
        hostname: mariadb-seafile.seafile.svc.cluster.local
        rootPasswordSecret:
          name: mariadb-seafile-secret
          key: MARIADB_ROOT_PASSWORD
    
    service:
      type: ClusterIP
      port: 80

  postRenderers:
    - kustomize:
        patches:
          - target:
              kind: StatefulSet
              name: seafile
            patch: |
              - op: add
                path: /spec/template/spec/containers/0/lifecycle
                value:
                  postStart:
                    exec:
                      command:
                        - /bin/sh
                        - -c
                        - |
                          sleep 30
                          if ! grep -q "CSRF_TRUSTED_ORIGINS" /opt/seafile/conf/seahub_settings.py 2>/dev/null; then
                            echo "" >> /opt/seafile/conf/seahub_settings.py
                            echo "# Custom configuration" >> /opt/seafile/conf/seahub_settings.py
                            echo "SERVICE_URL = 'https://seafile.hansjlachmann.net'" >> /opt/seafile/conf/seahub_settings.py
                            echo "FILE_SERVER_ROOT = 'https://seafile.hansjlachmann.net/seafhttp'" >> /opt/seafile/conf/seahub_settings.py
                            echo "CSRF_TRUSTED_ORIGINS = ['https://seafile.hansjlachmann.net']" >> /opt/seafile/conf/seahub_settings.py
                          fi
