apiVersion: source.toolkit.fluxcd.io/v1
kind: HelmRepository
metadata:
  name: seafile-server
  namespace: seafile
spec:
  interval: 1h
  url: https://charts.jetstack.io
---
apiVersion: source.toolkit.fluxcd.io/v1
kind: HelmRepository
metadata:
  name: bitnami
  namespace: seafile
spec:
  interval: 1h
  url: https://charts.bitnami.com/bitnami
