apiVersion: v1
data:
    db-password: ENC[AES256_GCM,data:7gDInWq3I+w=,iv:tnEsmbA9eRMCaMfQoneTFmyDIt+GXcFQuYDuInPKgDU=,tag:jRdPz447jXh4EgtwaD0K7g==,type:str]
    jwt-secret: ENC[AES256_GCM,data:8fwKD4K/MNO9/LQ12WSIZXMh2pxPSCcMe64BNW4vyx40V0co5eltiER5JIF9nL64SeaG7P3CdtRU/mK8nPx6Ing8QrE/Rcz7L9z+/m+PlivcDe5TPJ5DTQ==,iv:7yyqTqixvtx/Oe3mJXcCbZc3rPK1vXptPmXAqYQ7ahg=,tag:utzXeVozfASGtHZD/o+T+Q==,type:str]
kind: Secret
metadata:
    name: openerp-secret
sops:
    age:
        - recipient: age139rjwpu088h0a43s8xwspxpjnm9lhz29wv4zx6nzytvwxswutv6qf5vxe0
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSB5a1JMenAzaGxhMEdtVGF4
            RXFNb0N0ZW9KSTVQam1UeHEwbDQxdDJxdHdFCkpBeGhUR2ZjNzJJejc0QWJReVFJ
            bnZlREF6YTY4OUVwL2s4SHFMNFlwQVEKLS0tIE4vOEdTUjdJZzN1dVN6bGpjWUwv
            a0ZNS29Ec3orcGI2Y3REeU9hQzBOcXMKy9faW/BWvV3sC15RTyGdcqvpm6cMNE4n
            378Ykap3uHZuekVIfs5I0Wm0kxNgkgFHsJjMX0E6WWbqpPGNdVW0FQ==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2026-10-08T09:51:29Z"
    mac: ENC[AES256_GCM,data:lKvbhzo8jEjxOddbXd4oS1vmiArzjUdcurzHpM3zxMaYBTztX1hzP6RVnxrTTRhRln/d8i8uu5usc2qmicyxRP7ju7aIi/IeprhlrUelqonAtIu1nROGxl0oJ4ibmNKZmPVH+7kdUB2jMckUATu1ib3ek3D8EWnK/mgjko80r4I=,iv:+ABYUC8cWmeCdSI0M7NtncrbRbdkiczpEH6Nb0Y8FW8=,tag:sjSOhgZPZsM9L0UEDeyrPA==,type:str]
    encrypted_regex: ^(data|stringData)$
    version: 3.11.0
