apiVersion: v1
data:
    RENOVATE_TOKEN: ENC[AES256_GCM,data:dF6sCVJw5LGvhO3Ds8uB7xTrO3dzwSQa4dq4qzJEK1tojiShAyexVP9nMbV73o0XtjuRAM1oT8E=,iv:3PjZgbigjeJ7dRNcF8+buI8qej/YHqm1r+Qsu2SEH4U=,tag:4CFP1bqY+Eqtuz6s+FaX0Q==,type:str]
kind: Secret
metadata:
    name: renovate-container-env
sops:
    age:
        - recipient: age139rjwpu088h0a43s8xwspxpjnm9lhz29wv4zx6nzytvwxswutv6qf5vxe0
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSB0RC9MMmNoQzJaemNpd05q
            Q0VySmoxQ2Z0SGlGRUtTckM2cy9oVDlmT3c0CnoveFg4b3VPZGdrUnNoSEdJOXB6
            K2EvTG96OWhFUlJ3V2h4MWRqcjA3VW8KLS0tIE1kMC9jSjhuaVBSMkVZNndDQlFh
            eXRZY3VLUnRzc0YzUTJuSS9XZW1GRGcKR9jht79qH93xvsDvskxx85rlFt1EhNL6
            PqZy025caA2HCEVdlWXhVOBVr8Co6esr+8Q5M3dofCKJbObl/gth+w==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2026-07-19T09:28:50Z"
    mac: ENC[AES256_GCM,data:6cFl+3S1K38WCeLYxUji00X4wuAe1BJ6W3wyDQQ6tX6wew+LFm9/MlVa9SZUxSMmBC28mNGQ6XBENnkuzigcH9PYRlvQ00qc0GXz5HXxL0OPplzV0KuDpWNNdUEWcWQgJXCyFSvUVZVYwuXMudA8/oMAeF3dbUQGI96VzneQ5Dg=,iv:J6VKLn7VSFtWPqJLXyD42sYOGtoZGEskwslvKFEFWmU=,tag:BgwmM5LYabRDpUyYFshVaw==,type:str]
    encrypted_regex: ^(data|stringData)$
    version: 3.11.0
