apiVersion: v1
data:
    RENOVATE_TOKEN: ENC[AES256_GCM,data:56Ye28w0P2ei9NUN+2KCEWzxX0mtoODtausuvWWrIzQeA5FP6LEAg4lTQFlmmVmRVJUt7wzsXERJ,iv:WCATM2m0AXwHITpnCCTw+gZE70a9rpI910qNmRUSg0Y=,tag:3mYfKSbkeLB+H3069IWR7A==,type:str]
kind: Secret
metadata:
    name: renovate-container-env
sops:
    age:
        - recipient: age139rjwpu088h0a43s8xwspxpjnm9lhz29wv4zx6nzytvwxswutv6qf5vxe0
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBPaW5GdmM1K0pGazIwSFFR
            MG1YQWt0N201L3RUdjJLRHZSeWQzc1NmNW5FCm1JNTRPTnNJTnR5bnFocnA0YzRt
            T0dHcnFjUGRIZ3dreVlPZi9kVTJKK0EKLS0tIHlVanNxckQzVTdqdGFlT2E3QWpV
            ck9RaUE3VlBlanprWnUxMldKZ3FFSjAKC/eNFP4owLYdSNahcegsh9LTaKxMyxPV
            DqKQ0jI9rS4vELjXFO5/X3BoEydjP5UPusmY6LgTcZttwEpjrFtUHA==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2026-07-18T19:54:15Z"
    mac: ENC[AES256_GCM,data:Wi7jf/XUmyBFTjhegomq8Tu9q5ZQERy+4e552z/7Cxeer2X1w8inbnjTqGWa4szaOJNVxEv7IMBmYiYTQs/9kmja7zzAz0pL6z3cYrHLMTeX33P868wmA0fXAN4yXZhjtTNYRjth7mdFt5OmYy9U8stlFAD+yeIEstCFJWh3gFo=,iv:Yt9p1uHMVLnMZ7jaYb09oW5IEffddBcNyc29zWfuwAo=,tag:SDQBDpIjCkDqjmGCL+CXug==,type:str]
    encrypted_regex: ^(data|stringData)$
    version: 3.11.0
